# Generated by Django 6.0.4 on 2026-05-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='teleph_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
