# Generated by Django 6.0.4 on 2026-05-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agapp', '0002_booking_teleph_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='teleph_number',
            new_name='phone_number',
        ),
    ]
