# Generated by Django 6.0.4 on 2026-05-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agapp', '0003_rename_teleph_number_booking_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='agence_name',
            new_name='name',
        ),
    ]
