# Generated by Django 6.0.4 on 2026-05-14 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agapp', '0004_rename_agence_name_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack_travel',
            name='reservation_link',
        ),
        migrations.AddField(
            model_name='pack_travel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pack_travel',
            name='fiche_technique',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pack_travel',
            name='galerie_photos',
            field=models.ImageField(blank=True, null=True, upload_to='galerie_photos/'),
        ),
        migrations.AddField(
            model_name='pack_travel',
            name='image_circuit',
            field=models.ImageField(blank=True, null=True, upload_to='circuit_images/'),
        ),
        migrations.AddField(
            model_name='pack_travel',
            name='itinerary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='reser_circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('pack_travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agapp.pack_travel')),
            ],
        ),
    ]
