# Generated by Django 6.0.4 on 2026-05-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agapp', '0005_remove_pack_travel_reservation_link_pack_travel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
