# Generated by Django 6.0.4 on 2026-05-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agapp', '0007_paymentrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-check_in_date'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
    ]
