# Generated by Django 6.0.6 on 2026-06-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agapp', '0009_newslettersubscriber_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(default=33.7),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(default=3.0),
        ),
    ]
