# Generated by Django 6.0.6 on 2026-06-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agapp', '0010_destination_latitude_destination_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack_travel',
            name='latitude',
            field=models.FloatField(default=33.7),
        ),
        migrations.AddField(
            model_name='pack_travel',
            name='longitude',
            field=models.FloatField(default=3.0),
        ),
    ]
