# Generated by Django 6.0.6 on 2026-06-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingfou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_secteur', models.CharField(blank=True, max_length=50, null=True, verbose_name='SOUS_SECTEUR')),
                ('n_operati', models.IntegerField(blank=True, null=True, verbose_name='N_OPERATI')),
                ('chapitre', models.IntegerField(blank=True, db_column='CHAPITRE_', null=True, verbose_name='CHAPITRE_')),
                ('libelle_op', models.CharField(blank=True, max_length=255, null=True, verbose_name='LIBELLE_OP')),
                ('ap_initial', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='AP_INITIAL')),
                ('commune', models.CharField(blank=True, max_length=100, null=True, verbose_name='COMMUNE')),
                ('gest', models.CharField(blank=True, db_column='GEST_', max_length=50, null=True, verbose_name='GEST_')),
            ],
            options={
                'verbose_name': 'Enregistrement',
                'verbose_name_plural': 'Enregistrements',
                'db_table': 'ingfou',
            },
        ),
    ]
